<?xml version="1.0"?>
<package format="3">
  <name>openrobot_bringup</name>
  <version>0.1.0</version>
  <description>Top-level launch and configuration for OpenRobot-One.</description>
  <maintainer email="maintainers@openrobot.one">OpenRobot-One maintainers</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>openrobot_driver</exec_depend>
  <exec_depend>openrobot_gazebo</exec_depend>
  <exec_depend>openrobot_navigation</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  <test_depend>ament_cmake_pytest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
